name: Fetch and Store API Data

on:
  schedule:
    - cron: '0 13 * * *'  # 매일 오전 1시에 실행 (UTC), 한국시간 오후 10시

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas pymongo

      - name: Fetch and store data
        env:
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python fetch_and_store.py
